### ISSUE TITLE
Fix Logo Size on Mobile & Narrow Screens

### ISSUE THREAD

**Issue by michaellunzer** [michaellunzer/michaellunzer-portfolio#1]
- [ ] Figure out why my logo is so big on mobile screens

<img width="711" alt="Screen Shot 2020-07-06 at 1 15 33 AM" src="https://user-images.githubusercontent.com/10967175/86571554-7755de00-bf26-11ea-83a7-23e54899662e.png">

**Comment by charleskantz** [comment]
Hey Lunz! Looks like it’s this line in your style.css:

https://github.com/michaellunzer/michaellunzer-portfolio/blob/238296286fdd63f2e1b9dddc37fac3b2abc263c1/src/css/style.css#L192

It’s setting the the logo to be 100% of its container’s width, minus 30px. Since your logo is squareish it’ll  make the height naturally larger, and then big logo happens.

I dunno Gatsby so I’m not sure how the css plays into the framework, but you could adjust that value to be 50% or an explicit value like 150px.

**Comment by michaellunzer** [comment]
Thanks for looking into it @charleskantz -- I appreciate the explanation and advice 😎

It's all fixed and deployed now!
